backend:
  name: github
  repo: nocory/netlify-cms-loader-example-site
  branch: master
#publish_mode: editorial_workflow
media_folder: "src/uploads"
public_folder: "uploads"
site_url: "https://netlify-cms-loader.netlify.com"

collections:
  - name: "posts"
    label: "Post"
    folder: "src/cms/posts"
    slug: "{{year}}-{{month}}-{{day}}_{{hour}}-{{minute}}-{{second}}_{{slug}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}
  - name: "images"
    label: "Images"
    folder: "src/cms/images"
    slug: "{{year}}-{{month}}-{{day}}_{{hour}}-{{minute}}-{{second}}_{{slug}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Image, name: image, widget: image}
  - name: "files"
    label: "Files"
    files:
      - name: "pageStrings"
        label: "Page Strings"
        file: "src/cms/pageStrings.json"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Description, name: body, widget: markdown}
          - label: Column Titles
            name: columnTitles
            widget: list
            fields:
            - {label: Left, name: left, widget: string}
            - {label: Center, name: center, widget: string}
            - {label: Right, name: right, widget: string}