backend:
  name: github
  repo: nocory/netlify_cms
  branch: master
#publish_mode: editorial_workflow
media_folder: "src/uploads"
public_folder: "uploads"

collections:
  - name: posts
    label: Post
    folder: "src/cms/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}
      - {label: Categories, name: categories, widget: list}
      - {label: Tags, name: tags, widget: list, default: ['term_1', 'term_2']}
  - name: images
    label: Images
    folder: "src/cms/images"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Image, name: image, widget: image}